### PR TITLE
Added dracula wallpapers

### PR DESCRIPTION
**Pull request by classPythonAddike**
Added some more wallpapers from the dracula website, hope you like it! :wink:

### CODE REVIEW

**Review by Muhimen123 — CHANGES_REQUESTED** [review]
Thanks for the help! But can you put the new image information at the beginning of the list instead? (as stated in the [CONTRIBUTING.md](https://github.com/Muhimen123/TID/blob/main/CONTRIBUTING.md)) That will be a great help. 😊

**Comment by classPythonAddike** [comment]
sure

**Comment by classPythonAddike** [comment]
Changed :smilecat:

**Review by Muhimen123 — APPROVED** [review]
Thanks for the help and the wallpapers as well!

**Pull request merged**
